### ISSUE TITLE
README.md 추가 수정 요청

### ISSUE THREAD

**Issue by yunh03** [likelionknu11/challenger-page-backend#2]
현재 README.md의 프로필을 클릭하면, 사진 URL이 표시되고 팀원 개인 GitHub 프로필로 리다이렉트 되지 않습니다. 아래 링크에 리다이렉트가 가능한 수정된 README.md를 업로드 해 두었으니 수정 부탁드립니다!

[(https://github.com/yunh03/readmetestt/blob/main/README.md)](https://github.com/yunh03/readmetestt/blob/main/README.md)

**Comment by Dev-JihyeMoon** [comment]
넵 위 링크 내용으로 참고하여 main 브런치 수정 후 풀 리퀘스트 요청을 넣어두었습니다. 확인 후 승인 바랍니다.

**Comment by yunh03** [comment]
확인 후 승인 완료했습니다! 감사합니다.
